mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'base_to_lwheel'
  right_wheel: 'base_to_rwheel'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
